# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/socrates/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),socrates)

$(call add-radio-file-sha1-checked,radio/abl.img,08edf239ab1a2e574707f39f0799a9416928d402)
$(call add-radio-file-sha1-checked,radio/aop.img,89ef17f65fc1f91d67993dcb38f9728a1e0f86e2)
$(call add-radio-file-sha1-checked,radio/aop_config.img,773cf3df327f8f21d0997de5d7594cda35ee9046)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,cb558e7f9466258424d4cf4798b050d24589f9d1)
$(call add-radio-file-sha1-checked,radio/cpucp.img,85f33485e17c6fb31bc050caec698fc9412f01ec)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f1872ed85500f5c3f5ea7b66d246185a196f82cc)
$(call add-radio-file-sha1-checked,radio/dsp.img,763ca0c93788200e024ed16763144c3b67bc6bda)
$(call add-radio-file-sha1-checked,radio/featenabler.img,2bb1b87a8241871d3c70b679691dd55243125a1f)
$(call add-radio-file-sha1-checked,radio/hyp.img,d0ecbca7c7dd07bb8ad77d61520444f811836a7d)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e130a1d996b6188ceeb63c554687484800b56c10)
$(call add-radio-file-sha1-checked,radio/keymaster.img,789debe7ffb7b373f50cc1f3e36d110e99e5bffb)
$(call add-radio-file-sha1-checked,radio/modem.img,33a2667af83ff1a06a2d543ddd2de6b6b24cf73a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,18ad1f422b6db1161fd0a4a72496da8b1d1ddc5d)
$(call add-radio-file-sha1-checked,radio/shrm.img,889702446ad2e2af2f539fa63c778e7ab33ba064)
$(call add-radio-file-sha1-checked,radio/tz.img,964efc0643ed77c78e067ce9a4bcf54fcd95bb13)
$(call add-radio-file-sha1-checked,radio/uefi.img,982302c96719a2540b91bade28e241079b9c9061)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,bd3c8f9367b1b56d8947748371866be02af46a47)
$(call add-radio-file-sha1-checked,radio/xbl.img,a41885f5566d14d09eee64a4a8ddfbaa603225a0)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,ab7576c6d591d1699afda0c4ff663f2593146869)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,d223e05abd8cae63a49d1bb1c774ae76bb94293a)

endif
